# Generated by Django 5.2 on 2025-05-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('experience_year', models.IntegerField()),
                ('subject', models.CharField(choices=[('math', 'Math'), ('physics', 'Physics'), ('english', 'English')], max_length=100)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'db_table': 'teacher',
                'ordering': ['name'],
            },
        ),
    ]
